### ISSUE TITLE
Snare Fleas exiting vents still die immediately most of the time.

### ISSUE THREAD

**Issue by Clark919** [sam-k0/LC_FixCentipedeLag#2]
I still constantly come by open vents with dead fleas since the latest update. The modpack this issue is being noticed on is [here](https://thunderstore.io/c/lethal-company/p/TeamClark/TheMostLethalCompany/). If you need any logs, I can provide.

**Comment by sam-k0** [comment]
Hey, I think I know the issue of this. It's probably a dumb oversight by me, and I will fix it soon.
The issue is that I registered the hook method pre and postfix, which will artificially make the Centipede appear as stuck to my mod.
I'll fix it by the end of the day, thanks for your patience 😀

**Comment by sam-k0** [comment]
Along with a (hopefully) fixed behavior, I also allowed debug printing to be toggled.
It uses the Bepinex Logger, so you can disable Unity printing and still see the mod's logs. This makes it more easy to understand the behavior
